version: "3"

services: 
    app:
        build: 
            context: .
        ports: 
            - "8000:8000"
        volumes:
            - ./app:/app
        command: >
         sh -c "python manage.py runserver 0.0.0.0:8000"

# after setup command for build is:
    # $ docker-compose build
    # error fixed on: https://www.digitalocean.com/community/tutorials/how-to-install-docker-compose-on-ubuntu-18-04